/* Autogenerated by png2wx.pl on Mon May 23 13:54:18 2011 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

#include <wx/string.h>

extern void InitializeImages();

extern wxString g_svg_vdr;
extern wxString g_svg_vdr_play;
extern wxString g_svg_vdr_record;
extern wxString g_svg_play_rollover;
extern wxString g_svg_play_toggled;
extern wxString g_svg_record_rollover;
extern wxString g_svg_record_toggled;

extern wxString g_svg_settings;
extern wxString g_svg_file_open;
extern wxString g_svg_play_circle;
extern wxString g_svg_pause_circle;
extern wxString g_svg_stop_circle;

#endif /* ICONS_H */
