/* Autogenerated by png2wx.pl on Mon May 23 13:54:18 2011 */

#include <cstdint>

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/log.h>
#include <wx/mstream.h>
#include <wx/string.h>

#include "ocpn_plugin.h"
#include "icons.h"

wxString g_svg_vdr;
wxString g_svg_vdr_play;
wxString g_svg_vdr_record;
wxString g_svg_record_toggled;
wxString g_svg_record_rollover;
wxString g_svg_play_toggled;
wxString g_svg_play_rollover;

wxString g_svg_settings;
wxString g_svg_file_open;
wxString g_svg_play_circle;
wxString g_svg_pause_circle;
wxString g_svg_stop_circle;

void InitializeImages() {
  wxString tmp_path = GetPluginDataDir("vdr_pi");
  wxFileName fn;
  fn.SetPath(tmp_path);
  fn.AppendDir("data");

  fn.SetFullName("vdr_pi.svg");
  g_svg_vdr = fn.GetFullPath();

  fn.SetFullName("vdr_play.svg");
  g_svg_vdr_play = fn.GetFullPath();

  fn.SetFullName("vdr_record.svg");
  g_svg_vdr_record = fn.GetFullPath();

  fn.SetFullName("vdr_play_rollover.svg");
  g_svg_play_rollover = fn.GetFullPath();

  fn.SetFullName("vdr_play_toggled.svg");
  g_svg_play_toggled = fn.GetFullPath();

  fn.SetFullName("vdr_record_rollover.svg");
  g_svg_record_rollover = fn.GetFullPath();

  fn.SetFullName("vdr_record_toggled.svg");
  g_svg_record_toggled = fn.GetFullPath();

  fn.SetFullName("vdr_settings.svg");
  g_svg_settings = fn.GetFullPath();

  fn.SetFullName("vdr_file_open.svg");
  g_svg_file_open = fn.GetFullPath();

  fn.SetFullName("vdr_play_circle.svg");
  g_svg_play_circle = fn.GetFullPath();

  fn.SetFullName("vdr_pause_circle.svg");
  g_svg_pause_circle = fn.GetFullPath();

  fn.SetFullName("vdr_stop_circle.svg");
  g_svg_stop_circle = fn.GetFullPath();

  wxLogMessage("Loading toolbar icon: " + g_svg_record_toggled);
}
